Available_network:
  - alexnet:          alexnet
  - vgg:              vgg11, vgg11_bn, vgg13, vgg13_bn, vgg16, vgg16_bn, vgg19, vgg19_bn
  - resnet:           resnet18, resnet34, resnet50, resnet101, resnet152
  - densenet:         densenet121, densenet161, densenet169, densenet201
  - efficientnet:     efficientnet_b0, efficientnet_b1, efficientnet_b2, efficientnet_b3
                      efficientnet_b4, efficientnet_b5, efficientnet_b6, efficientnet_b7
  - efficientnet_v2:  efficientnet_v2_s, efficientnet_v2_m, efficientnet_v2_l
  - convnext:         convnext_tiny, convnext_small, convnext_base, convnext_large
  - mobilenet_v2:     mobilenet_v2
  - mobilenet_v3:     mobilenet_v3_large, mobilenet_v3_small
  - resnext:          resnext50_32x4d, resnext101_32x8d, resnext101_64x4d
  - shufflenet:       shufflenet_v2_x0_5, shufflenet_v2_x1_0, shufflenet_v2_x1_5, shufflenet_v2_x2_0
  - squeezenet:       squeezenet1_0, squeezenet1_1
  - wide_resnet:      wide_resnet50_2, wide_resnet101_2
  - vit:              vit_b_16, vit_b_32, vit_l_16, vit_l_32, vit_h_14

Available optimizer:
  - Adam
  - SGD
  - AdaGrad
  - AdamW

Available  lr_scheduler:
  - exponential
  - multiple_steps
  - cosine
  - reduce_on_plateau
  - clipped_cosine